/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ─── Multi-color accent system ───────────────────────────────
        brand: {
          terracotta:     '#c45d3e',
          terracottaLight:'#d97a5e',
          terracottaDark: '#a04a30',
          teal:           '#2a7d6e',
          tealLight:      '#3a9d8c',
          tealDark:       '#1e5f53',
          coral:          '#e8856c',
          coralLight:     '#f0a48f',
          coralDark:      '#c96a52',
          lavender:       '#8b7ec8',
          lavenderLight:  '#a99be0',
          lavenderDark:   '#6d60a8',
          gold:           '#c9a84c',
          goldLight:      '#d4b85c',
          goldDark:       '#a88e3a',
        },
        // ─── Light theme (default) ───────────────────────────────────
        gallery: {
          bg:           '#fdf8f3',
          surface:      '#f5efe6',
          card:         '#ffffff',
          cardHover:    '#faf6f0',
          border:       '#e8e0d4',
          borderHover:  '#d4c8b8',
          text:         '#1e1e1e',
          textSecondary:'#4a4a4a',
          textMuted:    '#7a7a7a',
          // ─── Dark theme ──────────────────────────────────────────────
          darkBg:         '#0f0f0f',
          darkSurface:    '#1a1a1a',
          darkCard:       '#222222',
          darkCardHover:  '#2a2a2a',
          darkBorder:     '#2e2e2e',
          darkBorderHover:'#3a3a3a',
          darkText:       '#f5f0e8',
          darkTextSecondary: '#c0b8a8',
          darkTextMuted:  '#8a8a8a',
        },
      },
      fontFamily: {
        display: ['Fraunces', 'Playfair Display', 'Georgia', 'serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'hero':   ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'hero-sm':['3rem',   { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'title':  ['2.25rem',{ lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'heading':['1.5rem', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'card':      '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.04)',
        'card-hover':'0 4px 16px rgba(0,0,0,0.08), 0 8px 32px rgba(0,0,0,0.06)',
        'elevated':  '0 8px 30px rgba(0,0,0,0.08)',
        'glow-terra':'0 0 20px rgba(196,93,62,0.25)',
        'glow-teal': '0 0 20px rgba(42,125,110,0.25)',
        'dark-card':      '0 1px 3px rgba(0,0,0,0.2), 0 4px 12px rgba(0,0,0,0.15)',
        'dark-card-hover':'0 4px 16px rgba(0,0,0,0.3), 0 8px 32px rgba(0,0,0,0.2)',
        'dark-elevated':  '0 8px 30px rgba(0,0,0,0.35)',
      },
      animation: {
        'fade-in':     'fadeIn 0.5s ease-out forwards',
        'fade-in-up':  'fadeInUp 0.6s ease-out forwards',
        'slide-up':    'slideUp 0.5s ease-out forwards',
        'scale-in':    'scaleIn 0.3s ease-out forwards',
        'pulse-soft':  'pulseSoft 2s ease-in-out infinite',
        'float':       'float 6s ease-in-out infinite',
        'shimmer':     'shimmer 2s linear infinite',
        'count-up':    'countUp 1s ease-out forwards',
      },
      keyframes: {
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp:  { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp:   { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        pulseSoft: { '0%, 100%': { opacity: '0.6' }, '50%': { opacity: '1' } },
        float:     { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        countUp:   { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
      backdropBlur: {
        xs: '2px',
      },
      transitionDuration: {
        '400': '400ms',
      },
    },
  },
  plugins: [],
};
