const PDFDocument = require('pdfkit');

/**
 * Generate a Certificate of Authenticity PDF
 * @param {Object} data - Certificate data
 * @param {string} data.certificateId - Unique certificate ID
 * @param {string} data.buyerName - Buyer's name
 * @param {string} data.artistName - Artist's name
 * @param {string} data.artworkTitle - Artwork title
 * @param {string} data.purchaseDate - Purchase date string
 * @param {number} data.editionNumber - Edition number (optional)
 * @param {number} data.totalEditions - Total editions (optional)
 * @param {number} data.amount - Purchase amount
 * @returns {Promise<Buffer>} PDF buffer
 */
const generateCertificate = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        layout: 'landscape',
        margins: { top: 60, bottom: 60, left: 80, right: 80 },
      });

      const buffers = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const centerX = pageWidth / 2;

      // Background
      doc.rect(0, 0, pageWidth, pageHeight).fill('#121212');

      // Gold border
      const borderMargin = 40;
      doc.rect(borderMargin, borderMargin, pageWidth - borderMargin * 2, pageHeight - borderMargin * 2)
        .lineWidth(2)
        .stroke('#c9a84c');

      // Inner border
      doc.rect(borderMargin + 8, borderMargin + 8, pageWidth - (borderMargin + 8) * 2, pageHeight - (borderMargin + 8) * 2)
        .lineWidth(0.5)
        .stroke('#c9a84c');

      // Header
      doc.font('Helvetica-Bold')
        .fontSize(12)
        .fillColor('#c9a84c')
        .text('ARTVAULT', centerX - 40, 75, { align: 'left' });

      doc.moveDown(1);

      // Title
      doc.font('Helvetica-Bold')
        .fontSize(28)
        .fillColor('#faf8f5')
        .text('Certificate of Authenticity', 0, 120, { align: 'center', width: pageWidth });

      // Decorative line
      doc.moveTo(centerX - 100, 160).lineTo(centerX + 100, 160).lineWidth(1).stroke('#c9a84c');

      // Certificate content
      const startY = 190;

      doc.font('Helvetica')
        .fontSize(11)
        .fillColor('#a0a0a0')
        .text('This certifies that', 0, startY, { align: 'center', width: pageWidth });

      doc.font('Helvetica-Bold')
        .fontSize(18)
        .fillColor('#faf8f5')
        .text(data.buyerName, 0, startY + 25, { align: 'center', width: pageWidth });

      doc.font('Helvetica')
        .fontSize(11)
        .fillColor('#a0a0a0')
        .text('is the verified owner of the digital artwork', 0, startY + 55, { align: 'center', width: pageWidth });

      doc.font('Helvetica-Bold')
        .fontSize(20)
        .fillColor('#c9a84c')
        .text(`"${data.artworkTitle}"`, 0, startY + 80, { align: 'center', width: pageWidth });

      doc.font('Helvetica')
        .fontSize(11)
        .fillColor('#a0a0a0')
        .text(`by ${data.artistName}`, 0, startY + 110, { align: 'center', width: pageWidth });

      // Edition info
      if (data.editionNumber && data.totalEditions) {
        doc.font('Helvetica-Bold')
          .fontSize(13)
          .fillColor('#faf8f5')
          .text(`Edition ${data.editionNumber} of ${data.totalEditions}`, 0, startY + 140, { align: 'center', width: pageWidth });
      }

      // Details row
      const detailsY = startY + 175;

      doc.font('Helvetica')
        .fontSize(9)
        .fillColor('#a0a0a0');

      const col1 = 120;
      const col2 = 340;
      const col3 = 550;

      doc.text('Certificate ID', col1, detailsY);
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#faf8f5')
        .text(data.certificateId, col1, detailsY + 15);

      doc.font('Helvetica').fontSize(9).fillColor('#a0a0a0')
        .text('Purchase Date', col2, detailsY);
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#faf8f5')
        .text(data.purchaseDate, col2, detailsY + 15);

      doc.font('Helvetica').fontSize(9).fillColor('#a0a0a0')
        .text('Amount', col3, detailsY);
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#faf8f5')
        .text(`₹${Number(data.amount).toLocaleString('en-IN')}`, col3, detailsY + 15);

      // Bottom line
      doc.moveTo(centerX - 150, detailsY + 55).lineTo(centerX + 150, detailsY + 55).lineWidth(0.5).stroke('#c9a84c');

      // Footer
      doc.font('Helvetica').fontSize(8).fillColor('#a0a0a0')
        .text('This certificate is generated by ArtVault and verifies the authenticity and ownership of the digital artwork described above.', 0, detailsY + 70, {
          align: 'center',
          width: pageWidth,
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateCertificate };
